# Simple workflow for deploying static content to GitHub Pages using pnpm
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  cancel-in-progress: true
  group: "pages"

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: npm i -g corepack@latest && corepack enable
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 23
      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Enforces lockfile usage strictly
      - name: Build
        run: pnpm build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
